### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by motorlatitude** [Blizzard/passport-bnet#15]
I keep getting the error mentioned in the title, the weird thing being that it does actually get an access token if I just refresh the callback page, so it just fails initially, sometimes it appears completely randomly? I can't seem to find a solution anywhere to this problem, maybe you guys have an idea, here is the whole stack trace:

```
InternalOAuthError: Failed to obtain access token
   at Strategy.OAuth2Strategy._createOAuthError (/var/www/ktj/node_modules/passport-oauth2/lib/strategy.js:370:17)
   at /var/www/ktj/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /var/www/ktj/node_modules/oauth/lib/oauth2.js:177:18
   at ClientRequest.<anonymous> (/var/www/ktj/node_modules/oauth/lib/oauth2.js:148:5)
   at emitOne (events.js:96:13)
   at ClientRequest.emit (events.js:188:7)
   at TLSSocket.socketErrorListener (_http_client.js:308:9)
   at emitOne (events.js:96:13)
   at TLSSocket.emit (events.js:188:7)
   at emitErrorNT (net.js:1272:8)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I think blizzard has been having server issues lately, so maybe it's just this?

**Comment by blizz-aurifex** [comment]
Apologies for the lack of response. I think I got this request confused with one on http://us.battle.net/forums/en/bnet/15051532/ and replied there. I suspect that this was caused by the DDoS attacks; has the issue cleared up since last week?

**Comment by motorlatitude** [comment]
No worries. Yes, everything is working fine now, I was just getting these errors as I was playing around with this module and thought maybe I was doing something wrong. It's been working fine for the last few days though so it most likely was just something to do with the DDoS attacks. Thanks!
