### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by sebarth** [Blizzard/passport-bnet#7]
Hey,

I try to use your plugin but I get an 302 response of the following request

https://us.battle.net/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fbnet%2Fcallback&client_id={myClientId}

I get redirected to

http://localhost:3000/auth/bnet/callback?error=invalid_request&error_description=Internal%20server%20error

I use your passport-bnet plugin with the suggested config.

```
AuthorizationError: Internal server error
   at Strategy.OAuth2Strategy.authenticate (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\passport-bnet\node_modules\passport-oauth2\lib\strategy.js:126:25)
   at attempt (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\passport\lib\middleware\authenticate.js:341:16)
   at authenticate (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\passport\lib\middleware\authenticate.js:342:7)
   at Layer.handle [as handle_request] (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\express\lib\router\layer.js:82:5)
   at next (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\express\lib\router\route.js:110:13)
   at Route.dispatch (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\express\lib\router\route.js:91:3)
   at Layer.handle [as handle_request] (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\express\lib\router\layer.js:82:5)
   at C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\express\lib\router\index.js:267:22
   at Function.proto.process_params (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\express\lib\router\index.js:321:12)
   at next (C:\Users\akrillo\IdeaProjects\osl-backend2\passport-bnet\examples\express\node_modules\express\lib\router\index.js:261:10)
```

I also tried your example express app and got the same error.

regards
Sebastian

**Comment by kelsin** [comment]
Can you email api-support@blizzard.com with your email that is linked to you dev.battle.net account so we can check into this?

**Comment by kelsin** [comment]
Also according to the line numbers on that error it looks like you might be using an older passport-bnet, can you make sure you're on version 1.1.1?

**Comment by sebarth** [comment]
I'm using 

`"passport-bnet": "^1.1.1"`

I think you can just check it by cloning this repo, install express, run your example express application after you update the id and secret key.

Using windows 7 x64

Also I sent an email to with my linked email to api-support@blizzard.com

regards

**Comment by kelsin** [comment]
Are you using a https redirect url? If not can you try that, we only support https redirect urls, that could be the issue.

**Comment by blizz-aurifex** [comment]
@sebarth, according to your original issue report you're using "http://localhost:3000/auth/bnet/callback” as your callback URL in your request. If you're using the default configuration in the Express demo app, the callback URL is set to "https://local.test.battle.net/auth/bnet/callback" [[source](https://github.com/Blizzard/passport-bnet/blob/master/examples/express/app.js#L43)]

Once you fix the HTTPS error @kelsin mentioned, you'll need to update the callback URL.

**Comment by sebarth** [comment]
alright this works flawless. Thank you guys. I should really point that out because many guys will run small http server with node without any motivation for using https :).

**Comment by kelsin** [comment]
Yes, we're looking into making the example app easier to use, cause right now it doesn't explain what you need to know. Thanks!
