### ISSUE TITLE
TokenError

### ISSUE THREAD

**Issue by adrielcodeco** [Blizzard/passport-bnet#9]
Hi,

First of all, your example dont use https but my code not work without https. Return error from blizz auth.

my solution:

http.createServer(app).listen(app.get('port'));
https.createServer({
    key: fs.readFileSync('\*\*\*.pem'),
    cert: fs.readFileSync('\*\*\*.pem')
}, app).listen(443);

Now, I had received this error with my code using your example.

TokenError: Internal server error
at Strategy.OAuth2Strategy.parseErrorResponse (/\*\*\*/node_modules/passport-bnet/node_modules/passport-oauth2/lib/strategy.js:298:12)
   at Strategy.OAuth2Strategy._createOAuthError (/\*\*\*/node_modules/passport-bnet/node_modules/passport-oauth2/lib/strategy.js:345:16)
   at /\*\*\*/node_modules/passport-bnet/node_modules/passport-oauth2/lib/strategy.js:171:43
   at /\*\*\*/node_modules/passport-bnet/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (/\*\*\*/node_modules/passport-bnet/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/\*\*\*/node_modules/passport-bnet/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:905:12)
   at nextTickCallbackWith2Args (node.js:455:9)

Any tips about how can i resolve?

**Comment by blizz-aurifex** [comment]
Annnd we're back. Sorry for the delay! Are you still running into this problem?

**Comment by adrielcodeco** [comment]
yes man.. I still can not solve.
apparently, the error not appears in the Authentication, the login is ok and after the solicitation of permission to access the account but after waiting a long time the server returns the internal error of token.

**Comment by blizz-aurifex** [comment]
What region are you using? I ask because I believe we're having some issues with CN at the moment.

**Comment by adrielcodeco** [comment]
US but i don't set region. because the US region is default

in strategy.js :
> options.region = options.region || 'us';

**Comment by blizz-aurifex** [comment]
Sorry for the delay. I'm juggling a couple other issues at the moment. I'm hoping I can dig into this in the next day or so. Worst case I'll lend a hand over the weekend.

**Comment by blizz-aurifex** [comment]
Finally have time time! I'm going to try get [this example](https://github.com/Blizzard/passport-bnet/tree/master/examples/express) up and running. Hopefully I can reproduce the issue you're seeing and advise on how to fix it :smile:

**Comment by blizz-aurifex** [comment]
I think the error you encountered may be caused by an intermittent OAuth issue we're having. Here's a link to a related issue on the API bug forums: [http://us.battle.net/en/forum/topic/20420282537](http://us.battle.net/en/forum/topic/20420282537). We tend to be more active on the forums than issue reports here. That said, I'll try to swing back this way once we've worked out a resolution.

**Comment by adrielcodeco** [comment]
hi man ... i have created this sample to help me to spend to you my problem ... https://ide.c9.io/adrielcodeco/bnettest

this workspace has a identical sample and not work to me

here is a url to app https://bnettest-adrielcodeco.c9users.io

**Comment by blizz-aurifex** [comment]
Closing out as there's been no activity on this in several months.
